Nastavit výchozí částku k vrácení dle táborové vratky
skaut/Skautske-hospodareni pull request #1516
Opened 2020-11-28 13:51 UTC by sinacek

close #1325

2020-11-29 16:13 UTC, fmasa requested changes
Mám jen pár drobností. Každopádně by IMO stálo za to uvést v tom UI s vratkami informaci o tom, že ty částky jsou přebraný s účastníků té akce (+ ideálně s proklikem na tu stránku).

2020-11-29 16:13 UTC, fmasa commented on app/model/DTO/Payment/RepaymentFactory.php
> +            $payment->getAmount(),
Tohle nesedí vůči zadání. Tam jsi psal, že výchozí částka má být `0`, pokud k té platbě neexistuje účastník s jinou částkou.

2020-11-29 16:13 UTC, fmasa commented on app/model/Payment/ReadModel/QueryHandlers/RepaymentCandidateListQueryHandler.php
> +            }
Tady lze použít kratší zápis:
```suggestion
            fn (DTO\Payment $payment) => $payment->getState()->equalsValue(State::COMPLETED),
```

2020-11-29 16:13 UTC, fmasa commented on app/model/Payment/ReadModel/QueryHandlers/RepaymentCandidateListQueryHandler.php
> +            fn(int $amount) => ($amount > 0)
Ta závorka tady nic nedělá.
```suggestion
            fn(int $amount) => $amount > 0
```

2020-11-30 12:37 UTC, sinacek commented on app/model/DTO/Payment/RepaymentCandidate.php
> +        ?string $bankAccount
tohle jde rovnou pak do template, takze bych to uz drzel jako string, abych to v sablone jednoduse vykleslil

2020-11-30 12:38 UTC, sinacek commented on app/model/DTO/Payment/RepaymentFactory.php
> +            $payment->getAmount(),
tohle odpovida aktualnimu stavu. Ale jsem otevrel obema moznostem

2020-12-04 16:21 UTC, sinacek commented
@fmasa ready na merge za mně

2020-12-07 18:10 UTC, fmasa commented on app/model/DTO/Payment/RepaymentFactory.php
> +            $payment->getAmount(),
Tohle je asi teda v pohodě. Nijak nepreferuji tu kterou možnost, takže klidně takto.

2020-12-07 18:12 UTC, fmasa commented on app/model/DTO/Payment/RepaymentCandidate.php
> +        ?string $bankAccount
To se používá jen v presenteru, ne? Do template to ani nejde. A i kdyby, tak je IMO furt lepší ty value objekty použít, cena za to je jedna extra zavolaná metoda, což IMO za to stojí.

2020-12-11 09:11 UTC, sinacek commented on app/model/DTO/Payment/RepaymentCandidate.php
> +        ?string $bankAccount
Používá se to jen jako default value ve formuláři. Já to beru z https://github.com/skaut/Skautske-hospodareni/blob/master/app/model/Payment/Payment/Transaction.php#L35 kde to je taky jako string, tak mě to nenapadlo měnit na objekt, když už to tady dostavam jako string a hned to zase budu pouzivat jako string

2020-12-11 09:11 UTC, sinacek commented
@fmasa odpověděl jsem oba dotazy a čekám na další review

2020-12-20 12:35 UTC, fmasa commented on app/model/DTO/Payment/RepaymentCandidate.php
> +        ?string $bankAccount
@sinacek To je jedno, že se to používá následně jako string. Ty value objekty mají dva hlavní přínosy:
- dokumentace - z API je jasně vidět, co to přijmá
- sanity check - nemůže se stát, že se tam někde dostane jinej string (zvlášť když ta metoda má víc string parametrů). Alternativa je v té metodě ten string validovat, což je ale oproti VO opruz.

2020-12-20 19:29 UTC, sinacek commented on app/model/DTO/Payment/RepaymentCandidate.php
> +        ?string $bankAccount
Upraveno

2020-12-20 19:29 UTC, sinacek commented
@fmasa ready na review

2020-12-21 16:37 UTC, fmasa approved these changes

2020-12-21 17:44 UTC, merged