remove ac_object
skaut/Skautske-hospodareni pull request #1574
Opened 2021-01-09 12:54 UTC by sinacek

close #880

2021-01-15 19:38 UTC, fmasa requested changes
Vypadá to good, jen prosím opravit pár drobností.

2021-01-15 19:38 UTC, fmasa commented on migrations/2021/Version20210109123938.php
> +        $this->savePairs(
Tady by bylo lepší použít jen [INSERT ... SELECT](https://dev.mysql.com/doc/refman/8.0/en/insert-select.html), než to načítat a iterovat nad tím

2021-01-16 11:52 UTC, sinacek commented
oboje upraveno

2021-01-16 16:50 UTC, fmasa approved these changes
LGTM. Nezapomeň pls na squash těch fixupů :)

2021-01-16 18:36 UTC, merged