Load payment details from Camp participants
skaut/Skautske-hospodareni pull request #2211
Opened 2023-05-15 20:10 UTC by juradee

2023-05-15 20:30 UTC, juradee commented
Proč selhává test na coding standart? Na devu projde. Dělám něco špatně?
![image](https://github.com/skaut/Skautske-hospodareni/assets/4532277/c5bf1c09-9e39-44a4-a090-40c88f6e9d6e)

2023-05-20 11:41 UTC, sinacek commented on app/model/DTO/Participant/PaymentDetails.php
> +            if ($date->isSaturday()) {
proč nepoužít `$date->modify('next monday');`

2023-05-20 11:51 UTC, sinacek requested changes
jen ta jedna poznámka, jinak to vypada ok

2023-05-22 08:58 UTC, juradee commented on app/model/DTO/Participant/PaymentDetails.php
> +            if ($date->isSaturday()) {
Protože je tam pak potřeba přetypování a ten kód mi připadá čitelnější.

2023-05-22 09:09 UTC, sinacek approved these changes

2023-05-22 18:50 UTC, merged