Updated na Bootstrap 5
skaut/Skautske-hospodareni pull request #2393
Opened 2023-10-15 19:52 UTC by marekdedic

- [ ] Carousel na hlavní stránce je nějaký rozbitý
- [ ] Dropdowny se zobrazují přes tlačítka

Obě tyhle věci budou vyžadovat update `bootstrap.native` a nejsou podle mě blocking.

2023-10-15 20:36 UTC, marekdedic commented
Testy lokálně nepustím kvůli #2379, takže :shrug:

2023-10-16 15:59 UTC, sinacek commented
> No, testy jsem nějak pustil různým mazáním a obnovováním složek, ale absolutně netuším, co je s nimi špatně - stěžuje si to, že nemůže kliknout na button, ale ve screenshotu je, když to samý udělám manuálně, tak je klikatelný a nic jsem nevygooglil 🤷

Neni potreba přidat wait nebo scroll?

2023-10-19 15:47 UTC, marekdedic commented
Hele já ty testy pustím 5x a dostanu 3 různý výsledky...

2023-10-19 18:22 UTC, marekdedic commented
No, tak teď to po malém fixu proběhlo... Bude to běžet stabilně i po mergnutí? Kdo ví...

2023-10-22 18:37 UTC, sinacek commented
<img width="543" alt="Screenshot 2023-10-22 at 20 36 44" src="https://github.com/skaut/Skautske-hospodareni/assets/1140123/372be821-67cf-458d-a4b3-3f4305b5aeca">

Na uvodni strance je ujeté tlacitko prihlasit se. 

> Obě tyhle věci budou vyžadovat update bootstrap.native a nejsou podle mě blocking.

Proč to mergovat bez dořešení těch 2 věcí?

2023-10-22 18:42 UTC, sinacek commented
<img width="250" alt="Screenshot 2023-10-22 at 20 42 35" src="https://github.com/skaut/Skautske-hospodareni/assets/1140123/0f8c2680-39e1-4566-a517-b4a7f65c593f">

2023-10-22 18:54 UTC, sinacek requested changes
viz komentare

2023-10-22 19:17 UTC, marekdedic commented
Udělal jsi `yarn install && yarn build`? Protože ty chyby vypadají, jako kdyby ne :D

Ad proč to mergovat bez těch 2 věcí: Protože ty vyžadují ještě update bootstrap.native, což jsem původně rozdělil do 2 PR - viz #2402, který obě chyby opravuje.

2023-10-23 08:07 UTC, juradee commented
@marekdedic dokončuji nový docker, kde už testy budou fungovat na 100% Předpokládám, že to bude na gitu ve středu.

2023-10-23 08:09 UTC, marekdedic commented
@juradee ok, tak na to s tímhle počkejme - až bude docker mergnutý, tak tady udělám rebase

2023-10-23 08:19 UTC, sinacek commented
> Udělal jsi yarn install && yarn build? Protože ty chyby vypadají, jako kdyby ne :D

zkusil jsem to znovu a vypada to stale stejne

2023-11-15 16:34 UTC, marekdedic commented
Test něběží, neumí kliknout na element, který je na screenshotu viditelný :shrug: Manuálně ověřeno, že to má správný tag a name a už na něj předtím klikal. Já ty testy opravit neumím, smazal bych je - flaky test je k ničemu, viz #2470...

2023-11-16 09:34 UTC, marekdedic commented
Tak tohle mě už vážně štve - dávám do toho testu:

```php
$I->waitForElementClickable('input[name="send"]');
$I->click('input[name="send"]');
```

 A ono mi to řekne na té druhé řádce "element click intercepted: Element is not clickable at point"

2023-11-16 10:59 UTC, marekdedic commented
> Moc jsem s tím nedělal, ale přišlo mi, že je to dost náchylné na zobrazené elementy a `$I->click()` potřebuje mít odscrollovaný display, kdežto některé jiní funkce hledají v DOMu

Jo, tak předchozí řádek je:

```php
$I->scrollTo('input[name="send"]');
$I->waitForElementClickable('input[name="send"]');
$I->click('input[name="send"]');
```

Náchylné to zcela určitě je :D

2023-11-16 11:06 UTC, juradee commented
> > Moc jsem s tím nedělal, ale přišlo mi, že je to dost náchylné na zobrazené elementy a `$I->click()` potřebuje mít odscrollovaný display, kdežto některé jiní funkce hledají v DOMu
> 
> Jo, tak předchozí řádek je:
> 
> ```
> $I->scrollTo('input[name="send"]');
> $I->waitForElementClickable('input[name="send"]');
> $I->click('input[name="send"]');
> ```
> 
> Náchylné to zcela určitě je :D

Já jen zařídíl, aby to chodilo na localhostu. Pokud se to chová rozdílně než na produkci, tak to můžu zkusit ještě poladit.

2023-11-23 13:38 UTC, marekdedic commented
Tak jsem ty testy nějak ohackoval...

Prosím @sinacek (a potenciálně @juradee ?) o review - pokud budete dělat i review kódu, tak bych udělal nejprve review tady, zamergoval to a pak zvlášť review #2402. Pokud to ale budete procházet jen vizuálně, asi bude jednodušší udělat review rovnou na #2402 a zamergovat obojí najednou. Díky!

2023-11-23 19:52 UTC, sinacek commented
Ja to projdu spis vizualne tedy rovnou https://github.com/skaut/Skautske-hospodareni/pull/2402 ale je mozny udelat rebase na dnesni master? menil jsem ta spousteni na macu a dalsi zavislosi aktualizoval, tak abych to videl rovnou

2023-11-23 22:57 UTC, marekdedic commented
Rebase dělám tak nějak občas, dnes jsem jen udělal, ale před mergnutím udělám znovu...

2023-11-25 21:00 UTC, merged