WIP: Fix dialog
skaut/Skautske-hospodareni pull request #2876
Opened 2024-10-18 11:53 UTC by juradee

2024-10-18 12:06 UTC, juradee commented
Není dořešené obecné volání handlu. Je to testovací řešení.

2024-10-22 14:00 UTC, juradee commented
Všechny dialogy v aplikaci musí nově dědit od třidy AccountancyModule/Components/Dialog.php

2024-10-23 13:05 UTC, marekdedic requested changes
Ještě jsem to neproklikal, ale zatím jsem našel tyhle věci:

- [nit] Některé soubory nekončí newline, viz tady v diffu
- Je potřeba odebrat výjimku pro updaty v `.github/dependabot.yml`, viz #2875 
- Je potřeba obdolete typy v `frontend/types/bootstrap.native/`, viz #2875

2024-10-23 16:54 UTC, marekdedic commented
Tak jsem to proklikal a lehce kouknul na kód a až na ty 3 věci mi to přijde dobrý. Díky!

2024-10-30 10:00 UTC, juradee commented
Upravil jsem nastavení pro dependabot a odebral ten jeden soubor. Nevím kde by měli být newline. `coding-standard` prošel a nic neopravil. Kdyžtek prosim @marekdedic o commit u těch věcí, kde se ti to nezdá. Díky

2024-10-30 10:26 UTC, marekdedic commented
Díky, jestli prošel coding-standard, tak v poho, za mě dobrý, dík!

2024-10-30 10:26 UTC, marekdedic approved these changes

2024-10-30 12:09 UTC, merged